# SPRING CORE
spring:
  application:
    name: demo
# OUTPUT
  output:
    ansi:
      enabled: detect
# PROFILES
  profiles:
    active: dev
# DATASOURCE
  datasource:
    url: jdbc:mysql://localhost:3306/sample_db?useSSL=false&allowPublicKeyRetrieval=true
    username: test_user
    password: test_user
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      maxActive: 4
      maxIdle: 4
      minIdle: 0
      initialSize: 4
# JPA
  jpa:
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  jackson:
    serialization:
      indent_output: true
      write-dates-as-timestamps: false
      write-durations-as-timestamps: true

# EMBEDDED SERVER CONFIGURATION
server:
  port: 9000
  context-path: /app

logging:
  level:
    root: info
    org.springframework: info
    com.example: debug

---

spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://db-server:3306/sample_db?useSSL=false&allowPublicKeyRetrieval=true
    username: test_user
    password: test_user
    driver-class-name: com.mysql.cj.jdbc.Driver

