# SPRING CORE
spring:
  application:
    name: demo
  beaninfo:
    ignore: true
# OUTPUT
  output:
    ansi:
      enabled: detect
# PROFILES
  profiles:
    active: dev
# DATASOURCE
  datasource:
    url: jdbc:mysql://localhost:3306/sample_db?useSSL=false
    username: test_user
    password: test_user
    driverClassName: com.mysql.jdbc.Driver
    defaultAutoCommit: false
    defaultReadOnly: false
    validationQuery: select 1
    timeBetweenEvictionRunsMillis: 3600000
    validationQueryTimeout: 3
    testOnBorrow: true
    testWhileIdle: true
    testOnConnect: true
    removeAbandoned: true
    removeAbandonedTimeout: 60
    logAbandoned: true
    maxActive: 4
    maxIdle: 4
    minIdle: 0
    initialSize: 4
# JPA
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

# EMBEDDED SERVER CONFIGURATION
server:
  port: 9000
  context-path: /app
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example: DEBUG
#    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
#    org.springframework.transaction: TRACE
#    org.hibernate: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.transaction: DEBUG
#    org.hibernate.jpa.internal: DEBUG
#    org.hibernate.event.internal: DEBUG
#    org.hibernate.engine.transaction.internal: DEBUG
#    org.hibernate.internal.util: DEBUG

---

spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql-server:3306/sample_db?useSSL=false
    username: test_user
    password: test_user
    driverClassName: com.mysql.jdbc.Driver
